### ISSUE TITLE
Get married

### ISSUE THREAD

**Issue by vsr** [vsr/life#2]

**Comment by arafatkamaal** [comment]
Finally this is just speculation/hypothesis, I have no experience whatsoever. So please verify this with the experts.

Firstly I'm equally clueless as much as you.

But think about it, how does one become a harmonica virtuoso or a expert programmer or a expert surgeon? Its by practice. You also have to work with the best people in the field. Skill and intelligence play its part, but you have to work very hard to be successful.

Getting a girl friend/wife is similar you have to spend a lot of time getting fashionable, learning and talking to the women of your dreams. And then when the things are about just right you need to make your moves with a proposal. But for that as I have said, you need to be determined, motivated and extremely hardworking in that area. Just like on programming you have to plan, set a goal and work towards getting a wife/girl friend. That involves first becoming a good friend, then spending hundreds of hours talking and then impressing that girl. Then giving gifts, then after all that you have to propose.

<b>What all this means is nerds like you and me with never get a girl friend ever!!!!!</b> Get used to it, because we can't no matter what. We are just not trained, motivated or ever remotely have the skill to purse such a project. Heck we don't have a slightest clue about it.

Therefore the only way out is trust your parents to find a girl for you. With a little filtering and searching you will eventually get there.

**Comment by hiway** [comment]
Since it's already being tracked as an issue, I'm going to consider that the required tasks for achieving this goal will be taken.

**Comment by hiway** [comment]
Elaborate! :P
